# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: zopfli-bin 0.1.0 ruby lib
# stub: ext/extconf.rb

Gem::Specification.new do |s|
  s.name = "zopfli-bin"
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib"]
  s.authors = ["Chetan Sarva"]
  s.date = "2014-10-21"
  s.description = "A thin wrapper around the zopfli binary (included and built as an ext)"
  s.email = "chetan@pixelcop.net"
  s.extensions = ["ext/extconf.rb"]
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    ".gitmodules",
    ".testguardrc",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "ext/Makefile",
    "ext/extconf.rb",
    "lib/zopfli-bin.rb",
    "lib/zopfli/bin.rb",
    "test/helper.rb",
    "test/test_zopfli-bin.rb",
    "vendor/zopfli/CONTRIBUTORS",
    "vendor/zopfli/COPYING",
    "vendor/zopfli/Makefile",
    "vendor/zopfli/README",
    "vendor/zopfli/README.zopflipng",
    "vendor/zopfli/src/zopfli/blocksplitter.c",
    "vendor/zopfli/src/zopfli/blocksplitter.h",
    "vendor/zopfli/src/zopfli/cache.c",
    "vendor/zopfli/src/zopfli/cache.h",
    "vendor/zopfli/src/zopfli/deflate.c",
    "vendor/zopfli/src/zopfli/deflate.h",
    "vendor/zopfli/src/zopfli/gzip_container.c",
    "vendor/zopfli/src/zopfli/gzip_container.h",
    "vendor/zopfli/src/zopfli/hash.c",
    "vendor/zopfli/src/zopfli/hash.h",
    "vendor/zopfli/src/zopfli/katajainen.c",
    "vendor/zopfli/src/zopfli/katajainen.h",
    "vendor/zopfli/src/zopfli/lz77.c",
    "vendor/zopfli/src/zopfli/lz77.h",
    "vendor/zopfli/src/zopfli/squeeze.c",
    "vendor/zopfli/src/zopfli/squeeze.h",
    "vendor/zopfli/src/zopfli/tree.c",
    "vendor/zopfli/src/zopfli/tree.h",
    "vendor/zopfli/src/zopfli/util.c",
    "vendor/zopfli/src/zopfli/util.h",
    "vendor/zopfli/src/zopfli/zlib_container.c",
    "vendor/zopfli/src/zopfli/zlib_container.h",
    "vendor/zopfli/src/zopfli/zopfli.h",
    "vendor/zopfli/src/zopfli/zopfli_bin.c",
    "vendor/zopfli/src/zopfli/zopfli_lib.c",
    "vendor/zopfli/src/zopflipng/lodepng/lodepng.cpp",
    "vendor/zopfli/src/zopflipng/lodepng/lodepng.h",
    "vendor/zopfli/src/zopflipng/lodepng/lodepng_util.cpp",
    "vendor/zopfli/src/zopflipng/lodepng/lodepng_util.h",
    "vendor/zopfli/src/zopflipng/zopflipng_bin.cc",
    "vendor/zopfli/src/zopflipng/zopflipng_lib.cc",
    "vendor/zopfli/src/zopflipng/zopflipng_lib.h",
    "zopfli-bin.gemspec"
  ]
  s.homepage = "http://github.com/chetan/zopfli-bin"
  s.licenses = ["MIT"]
  s.rubygems_version = "2.2.2"
  s.summary = "A thin wrapper around the zopfli binary"

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<mixlib-shellout>, [">= 0"])
      s.add_development_dependency(%q<yard>, ["~> 0.7"])
      s.add_development_dependency(%q<bundler>, ["~> 1.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 2.0.1"])
      s.add_development_dependency(%q<micron>, [">= 0"])
      s.add_development_dependency(%q<test_guard>, [">= 0"])
      s.add_development_dependency(%q<rb-inotify>, [">= 0"])
      s.add_development_dependency(%q<rb-fsevent>, [">= 0"])
      s.add_development_dependency(%q<rb-fchange>, [">= 0"])
    else
      s.add_dependency(%q<mixlib-shellout>, [">= 0"])
      s.add_dependency(%q<yard>, ["~> 0.7"])
      s.add_dependency(%q<bundler>, ["~> 1.0"])
      s.add_dependency(%q<jeweler>, ["~> 2.0.1"])
      s.add_dependency(%q<micron>, [">= 0"])
      s.add_dependency(%q<test_guard>, [">= 0"])
      s.add_dependency(%q<rb-inotify>, [">= 0"])
      s.add_dependency(%q<rb-fsevent>, [">= 0"])
      s.add_dependency(%q<rb-fchange>, [">= 0"])
    end
  else
    s.add_dependency(%q<mixlib-shellout>, [">= 0"])
    s.add_dependency(%q<yard>, ["~> 0.7"])
    s.add_dependency(%q<bundler>, ["~> 1.0"])
    s.add_dependency(%q<jeweler>, ["~> 2.0.1"])
    s.add_dependency(%q<micron>, [">= 0"])
    s.add_dependency(%q<test_guard>, [">= 0"])
    s.add_dependency(%q<rb-inotify>, [">= 0"])
    s.add_dependency(%q<rb-fsevent>, [">= 0"])
    s.add_dependency(%q<rb-fchange>, [">= 0"])
  end
end

